FROM python:3.13-slim

WORKDIR /app
{% if has_git_deps %}
COPY requirements.docker.txt ./requirements.txt
{% else %}
COPY requirements.txt .
{% endif %}
RUN pip install --no-cache-dir -r requirements.txt
{% if sdk_local %}

COPY pyproject.toml .
COPY src/ src/
RUN pip install --no-cache-dir .
{% endif %}

COPY {{ service_file }} .
COPY lynxConf.json .

CMD ["python", "{{ service_file }}"]
